name = "independence/smart-contract"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'independence/smart-contract'"

[repository]
user = "independence"
project = "smart-contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
